### ISSUE TITLE
Annotation mode: handling 'ArrayIndexOutOfBounds' in the end

### ISSUE THREAD

**Issue by vzinche** [mobie-org/mobie#15]
At the moment, while annotating the cells once you reach the end it (1) doesn't inform you that you're finished and (2) throws java.lang.ArrayIndexOutOfBoundsException

Could you catch this exception somehow? Maybe something like disallowing the button 'select next' if there is no next index? Or even showing a notification 'You've reached the end'?

**Comment by tischi** [comment]
Not sure what is going on. When I click 'next' and there is nothing more to come it simply does not do anything. 

In the code of the 'next' button it checks `if ( rowIndex < tableRows.size() - 1 )`
So it should not do anything if you are at the end.
Even if the remaining items are all `None` it should work according to the code. 

```
next.addActionListener( e ->
		{
			isSingleRowBrowsingMode = true;

			int rowIndex = currentlySelectedRowIndex;
			if ( rowIndex < tableRows.size() - 1 )
			{
				T row = null;
				if ( skipNone )
				{
					while ( rowIndex < tableRows.size() )
					{
						row = tableRows.get( rowSorter.convertRowIndexToModel( ++rowIndex ) );
						if ( isNoneOrNan( row ) )
						{
							row = null;
							continue;
						}
						else
							break;
					}
					if ( row == null )
					{
						return; // None of the next rows is not None
					}
				}
				else
				{
					row = tableRows.get( rowSorter.convertRowIndexToModel( ++rowIndex ) );
				}

				selectRow( row );
			}
		} );
```

Can you maybe show a specific case? Maybe it is some border case that I am not considering....
And also show me the error message?

**Comment by tischi** [comment]
...ah I think I can reproduce it. It has to do with the fact that the column is sorted according to something and not in the initial order. I will have a look...

**Comment by vzinche** [comment]
Oh, great. Because I was struggling to reproduce it now :D

**Comment by tischi** [comment]
Yes, super confusing with the table being sorted in different ways. Maybe I found a clean way now to handle it....
Please try with replacing this jar:
**/g/cba/exchange/mobie/jars/imagej-utils-0.5.0.jar**

**Comment by vzinche** [comment]
Will do! In the meantime I managed to reproduce it (if it still helps):
![Screenshot from 2020-07-14 15-41-22](https://user-images.githubusercontent.com/32451366/87432961-06c75500-c5e9-11ea-9922-4f49a5508f2f.png)

**Comment by tischi** [comment]
that's the error i got as well, let's see whether I managed to fix it.

**Comment by vzinche** [comment]
Yeah, this time it gave me a 'no more segments' notification!
Looks great, thanks :)
