### ISSUE TITLE
Grid view of many sources

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#20]
It would be great to come up with a way to store and present many sources in a sort of grid view.

Use cases:
1. HTM screening microscopy (multi-well plates)
1. Data that is convenient to see next to each other even though it has no obvious spatial relationship, e.g.
    - Many tomograms
    - Many images of drosophila expression different genes. 

For the second use case: In principle one could also just always look at one of the images and then switch to another one. However, I feel it could be more convenient to have them side by side (in a grid) and then laterally move around from one image to another in BDV (rather then replacing the image by another one). I think reasons could be that 
1. one could arrange them such that one can really compare, e.g., two images side-by-side. 
1. maybe it is some psychological thing, but if all images are "laid out" on a 2D map, one feels like "having control" over the whole data set and sort of walking around in the data set landscape. Maybe even building some internal map like: "Ah,  this interesting image was on the top right".

What do you think about the use cases?

Do you have proposals for how to implement this? 
For now in our "old" n5 based format, but of course having this in mind: https://forum.image.sc/t/ome-ngff-combine-multiple-images-into-one-dataset/47619/10
Critical for us would be the link from this "grid of images" to an "image feature table" (not sure we have to define a new data structure for this or we just reuse (as we did so far) the image segments logic....

**Comment by K-Meech** [comment]
It would be worth talking to Yannnick about this - as he is very keen on using grids for his data. (I don't think he's on github though?)

I think grids can be very useful for certain datasets! I see a lot of the people in the lab wanting to compare between datasets by seeing them side by side. Where it becomes difficult though, is when the number of images is very large i.e. they want to compare a dataset at the very top left with one at the very bottom right of the grid.

I wonder if a more flexible solution would be possible? e.g. the position of datasets is just controlled by the affine transform given in the xml right? So would it be possible to have this as a parameter in a bookmark, for example? Then we could provide some convenience functions to calculate these transforms for different grids.

This would then allow the use case of say: viewing one image at a time, then having a bookmark to view a full grid, or to view grids of interesting subsets of the data... This is more complex with tables though, if the positions can change...

**Comment by constantinpape** [comment]
I agree that this would be very useful (we have seen the use-case for the tomogram dataset already, but there the solution where we rewrote all the data was sub-optimal).

@tischi In your mail you wrote "it looks like as if the new version of BDV can (now with good performance) display hundreds of sources in parallel". Does that mean that all sources are in the same BDV viewer window or can you also have multiple BDV windows in parallel, each with its own source?

I am asking this because I can see two options of how to generate the grid view:
1. Open a single BDV window and place the sources in the grid by applying the correct affine transformation. (I think this is also what @K-Meech suggested.)
2. Open a separate BDV window for each source and arrange them in a grid. Sync the viewer interactions between the different windows.

The data format would depend on which of these two solutions we implement: for the second one we wouldn't need to compute affine transforms at all and would just need to specify the positions in terms of grid coordinates.
For the first solution we would need to translate the grid coordinates into affine transformations (either explicitly in the xml or this could also be done implicitly on the viewer side).

p.s. Yannick is on github, cc @yanschwab

**Comment by K-Meech** [comment]
Having multiple bdv windows would be very useful! One of the main issues with having the images in a fixed grid, is it makes it hard to compare datasets with very different dimensions. e.g. one with a much smaller z depth than the other. Multiple bdv windows would make it a lot easier to compare different parts of different datasets.

**Comment by tischi** [comment]
> 1 .Open a single BDV window and place the sources in the grid by applying the correct affine transformation. (I think this is also what @K-Meech suggested.)
> 2. Open a separate BDV window for each source and arrange them in a grid. Sync the viewer interactions between the different windows.

I meant (1) and would also strongly vote for (1) because then we can use all the source grouping logic that comes with BDV. In addition, and that's addressing @K-Meech 's question, we can them implement logic to change the source's affine transformations on the fly such that they could be reordered as the user wishes. Have you seen the NEUBIAS webinar on big image data last week? @nicokiaru showed a lot of impressive stuff as to how to reshuffle the spatial arrangement of many sources  in BDV, so there's already a nice code base for this! @nicokiaru, is there maybe a youtube video this (incl. the bdv-selector)?

**Comment by tischi** [comment]
> One of the main issues with having the images in a fixed grid, is it makes it hard to compare datasets with very different dimensions.

I agree, but I was also mainly thinking of the grid as being useful for images of the same dimensions. If they have different dimensions I am not sure what to do. Maybe this is an entirely different use case that requires a different approach?

**Comment by yanschwab** [comment]
I like the concept of grids very much, especially when progressing through a project and when comparisons are necessary. It is true that it looks ugly, but it's convenient. I'm building manually such a grid from multiple FIBSEM datasets. Can show it to you at some point.

**Comment by tischi** [comment]
> is true that it looks ugly

@yanschwab  Could you post a screenshot here? I'd like to understand in which sense it is ugly :-)

**Comment by yanschwab** [comment]
![Screenshot 2021-01-19 at 15 48 41](https://user-images.githubusercontent.com/66484560/105050330-f4cddf80-5a6d-11eb-95fa-c15df0e9043f.png)

**Comment by yanschwab** [comment]
as Kimberly said, when images don't have the same dimensions, it does not yield a nice array

**Comment by tischi** [comment]
> as Kimberly said, when images don't have the same dimensions, it does not yield a nice array

There is a way to manually move around those files in BDV. Not sure, maybe it even works already now. I would have to try. Can I access this data?

**Comment by constantinpape** [comment]
> I meant (1) and would also strongly vote for (1) because then we can use all the source grouping logic that comes with BDV. In addition, and that's addressing @K-Meech 's question, we can them implement logic to change the source's affine transformations on the fly such that they could be reordered as the user wishes. Have you seen the NEUBIAS webinar on big image data last week?

@tischi  thanks for clarifying and this makes a lot of sense. 
So the way I understand this now, we would only need a specification for the grid source that defines the (initial) grid coordinates for the "tile source" (and MoBIE / BDV will take care of computing the affines and reordering).

If we want to stick with our current `images.json` format, we could for example add `"type": "grid"` like this:
```
{
"grid-source-name": {
  "type": "grid",
  "gridSize": [2, 2],
  "storage": {
    "local": ["/path/to/tileSource1.xml", ..., "/path/to/tileSource4.xml"],
    "remote": [...]
  },
  # we use the same indexing as in "storage:local", so this needs to have the same length
  # (but we don't need to fill all grid positions)
  "initialGridPositions": [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
  ],
  # and other fields like color, contrast limits etc
}
}
```

**Comment by tischi** [comment]
Yes, something like this! 

0. I want to say we should not "overdo" it as in the long run we may want to use the "official" ome.ngff solution for this. However, either we implement our own solution or not. Any opinions whether we should wait for an ome.ngff spec or whether we should go ahead with an own (bdv/xml/n5) spec? cc @joshmoore
1. One question would be whether the burden of computing the affine transforms is on MoBIE's side or on the side of the "thing" creating the .json file ;-) But I think you are right, maybe let MoBIE do the job.
2. Any ideas where we store the "image feature table" and how we ensure the correct mapping from table rows to the images in the grid?
3. Should we just give it a try with a test project? Maybe make a branch of the Covid tomograms?

**Comment by yanschwab** [comment]
I tried and moving the images around is very easy. But nothing is stored so next time the project is opened, I am back at the beginning.

**Comment by constantinpape** [comment]
>     1. I want to say we should not "overdo" it as in the long run we may want to use the "official" ome.ngff solution for this. However, either we implement our own solution or not. Any opinions whether we should wait for an ome.ngff spec or whether we should go ahead with an own (bdv/xml/n5) spec? cc @joshmoore

I think it would be best if we try our luck first and then use the experiences we gain to contribute to the ome.ngff.
There is not so much we  need to add in the json anyway.

>     2\. One question would be whether the burden of computing the affine transforms is on MoBIE's side or on the side of the "thing" creating the .json file ;-) But I think you are right, maybe let MoBIE do the job.

I think it would be better if MoBIE can do it, then there is less room for error (because we don't have to rely that the affines computed externally are correct). Also, if we want to support reordering images on the grid the transformations need to be recomputed in any case.

 >     3\. Any ideas where we store the "image feature table" and how we ensure the correct mapping from table rows to the images in the grid?

Good point. We can add another field `"table": "/path/to/table.csv"` and the table has a column `image_id` (which again is the index used for "storage:local").

>     4\. Should we just give it a try with a test project? Maybe make a branch of the Covid tomograms?

Sounds good. I can make a small test project there later with the layout we discussed above.

**Comment by tischi** [comment]
> I tried and moving the images around is very easy. But nothing is stored so next time the project is opened, I am back at the beginning.

@yanschwab as discussed by mail, you could talk to @K-Meech if the arrangement of sources could be stored into a bookmark. Along those lines: In BDV itself (not MoBIE) there is a Menu item: [ File > Save Settings ]. You could explore what is saved there. I _think_ this stores also the manual transformations of all the sources. If that is true, we could maybe try to find the source code of this and re-use some of the logic to save this information into a MoBIE bookmark.

**Comment by constantinpape** [comment]
I created a branch with a test dataset according to the idea proposed above: https://github.com/mobie/covid-tomo-datasets/tree/grid-test.

I haven't uploaded the data for this to s3, but it's on the group-share: `/g/kreshuk/pape/Work/mobie/covid-tomo-datasets`.

**Comment by K-Meech** [comment]
Just talked to Timothy about his data, and the grid view would for sure be useful! It would need to be flexible so you can view the images on top of eachother (in the usual mobie way), and then switch to a grid. I think @constantinpape 's suggestion covers this use case nicely.

**Comment by tischi** [comment]
@constantinpape 

https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/images/images.json

Should we also have the individual images there in the images.json?
What about something like this?
```
{
  "em-tomogram-1": { storage .. },
  "em-tomogram-2": {},
  "em-tomogram-3": {},
  "em-tomogram-4": {},
  "collection-em-tomograms-grid-view": {
    "layout": "auto-grid",
    "storage": {
      "remote": [
        "remote/em-tomogram-1.xml",
        "remote/em-tomogram-2.xml",
        "remote/em-tomogram-3.xml",
        "remote/em-tomogram-4.xml"
      ]
    },
   "collection-em-tomograms-grid-view": {
    "layout": "auto-grid",
    "images": { "em-tomogram-1", "em-tomogram-2", "em-tomogram-3", "em-tomogram-4"}
   }
  "collection-em-tomograms-favorites": {
    "layout": "auto-grid",
    "images": { "em-tomogram-2", "em-tomogram-3"}
   }
```

Then in the MoBIE UI there could be two drop-down menus: `em` and `collection`.

**Comment by constantinpape** [comment]
Yes, I think having 
```
{
  "em-tomogram-1": {...},
  ...,
  "collection-em-tomograms": {
     "images": [...],
     "gridPositions": [...],
      ....
  }
}
```
is a good solution.

**Comment by constantinpape** [comment]
I have updated the metadata [here](https://github.com/mobie/covid-tomo-datasets/tree/grid-test) as we discussed and I have also uploaded the example data to s3.

**Comment by tischi** [comment]
Thanks a lot! I will only have time in two weeks from now to work on it. 
In fact, I got a little heart attack getting an e-mail reminder right now that I should give a presentation about MoBIE next week during a NEuBIAS webinar next week Wednesday afternoon! Would you be motivated to contribute a little bit?!!!
I will send a mail.

**Comment by tischi** [comment]
Hi all,

I have been looking at this...

Adding a new new datatype "collection" to the images.json is not straightforward, because a lot of the downstream logic in the code depends on this being a simple list of images, i.e. individual `Sources`. 

One option is to treat a collection as one single `Source`, but then we would have to think about implementing some sort of `GridSource` that constructs one source out of the many. This is doable, but some work. I asked in gitter whether someone did that already.

I realized that an alternative could be to handle the grid view on the level of the bookmarks. This would be initially easier because in the bookmarks there we already have the logic to show multiple sources (aka layers) together. Thus, we would need less changes in the code. So we could think of adding the `"layout": "auto-grid"` to the bookmarks instead. In some sense I like this as Bookmarks could also be seen as particular views on the data. I checked, and in this scenario, I think we can, relatively easily, use the BDV internal logic of grouping sources in order to bind their display settings.

What do you think?

**Comment by constantinpape** [comment]
> I realized that an alternative could be to handle the grid view on the level of the bookmarks. This would be initially easier because in the bookmarks there we already have the logic to show multiple sources (aka layers) together. Thus, we would need less changes in the code. So we could think of adding the `"layout": "auto-grid"` to the bookmarks instead. In some sense I like this as Bookmarks could also be seen as particular views on the data. I checked, and in this scenario, I think we can, relatively easily, use the BDV internal logic of grouping sources in order to bind their display settings.

Yes, I think this is a good solution.

I am sitting in on the NGFF call, and at some point there will be a better `collection` specification, which would be nice to support as a grid source. But for the time being, I think having it as bookmarks is a perfectly fine solution.

**Comment by tischi** [comment]
Cool! 
If you find the time maybe you could amend the example accordingly?
https://github.com/mobie/covid-tomo-datasets/tree/grid-test

**Comment by constantinpape** [comment]
Yes, will let you know when I have it.

**Comment by K-Meech** [comment]
Yes - sounds good! It would be great if this could all be handled with bookmarks.

**Comment by tischi** [comment]
@constantinpape @K-Meech 

I had a look and the easiest may be to re-use the `layers` field to specify the individual image sources (even though they are not shown on top of each other, which makes the naming `layers` a bit unfortunate).
Then we could add a field `collection` in which all names of the `layers` are given, which should be shown in a specified `layout`. We could also already do it such that there could be several collections as this would allow us to put different layers on top of each other (like HTM multi-color images).

If we go for this, in principle, I feel we should really (at some point) rename `layers` to `sources` though.

**Comment by constantinpape** [comment]
> I had a look and the easiest may be to re-use the `layers` field to specify the individual image sources (even though they are not shown on top of each other, which makes the naming `layers` a bit unfortunate).

Makes sense.

> Then we could add a field `collection` in which all names of the `layers` are given, which should be shown in a specified `layout`. We could also already do it such that there could be several collections as this would allow us to put different layers on top of each other (like HTM multi-color images).

Also makes sense. We could maybe have `"layout": "auto-grid", "stack"` (and more complex option later) to support the different options.
Just to make sure I understand your proposal correctly, for our tomogram example, the bookmark should look like this:
```json
{
"gridView": {
    "layers": ["tomo1", "tomo2", "tomo3", "tomo4"],
    "collection": ["tomo1", "tomo2", "tomo3", "tomo4"],
    "layout": "auto-grid"
  }
}
``` 

> If we go for this, in principle, I feel we should really (at some point) rename `layers` to `sources` though.

That would be fine with me.

**Comment by tischi** [comment]
I was more thinking:
```
{
"collections": {
     "someName":
     {
        "layers": ["tomo1", "tomo2", "tomo3", "tomo4"],
        "layout": "auto-grid"
     }
     "someOtherName":
     {
      ....
     }
  }
}
```
But maybe we do not need several collections... we could handle this within the layout, I guess...

**Comment by constantinpape** [comment]
@tischi I like your suggestion more and was actually thinking to propose something along these lines.
I will update the example later and let you know when it's there.

**Comment by tischi** [comment]
...since it is a bookmark with multiple layers it is actually already clear that it is a "collection" of images.
Thus, maybe some other name, maybe `layouts` instead of `collections`?
The point being that some of the displayed sources "are to be laid out"?

**Comment by constantinpape** [comment]
I have updated the bookmark: https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/misc/bookmarks/default.json

**Comment by tischi** [comment]
@K-Meech @constantinpape 

First version working!

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/2157566/108875104-1e45d200-75fd-11eb-97c8-b5442a5d2c4a.png">

Questions:

0. I slightly renamed some things in the Bookmark as this made more sense with the way my Java code currently works. OK?
1. How to determine the spacing between the sources? For now I implemented 10% of the width of the first source
2. What to do if the size of the sources is not the same? Maybe `AutoGrid` should only be allowed for sources of same size (and maybe be renamed to `EquidistantGrid`)? Otherwise maybe there are cool algorithms that optimally pack a bunch of images of unequal size?!
3. What about the display settings? As you can see in the screenshot, currently it adds all sources individually to the sources panel, which will clutter the UI. I think we should have just one B&C control for all sources in one layout (at least for some of the `LayoutType`). But then we should reflect this also in the Bookmark, i.e. specify the `contrastLimits` for the whole layout.

**Comment by K-Meech** [comment]
Cool! Looks great!
0. Fine with me
1. 10% of width sounds good
2. I think renaming to EquidistantGrid would be a good plan - it makes it clear that it only works well with images of the same size. For images of unequal size: I guess if you place each image so their central z position is aligned, it becomes a problem of packing rectangles in 2D. I imagine there are some cool algorithms out there! It's a very similar problem to e.g. making sprite sheets or texture atlases for video games where they pack many arbitrarily shaped 2D images into a small area. Would be cool to look into.
3. I agree - it'd be nice if there was one control for all sources in a layout to avoid cluttering the UI. Perhaps you could have contrastLimits for the layout, and this overrides any contrastLimits given for the individual layers?

**Comment by constantinpape** [comment]
Yes, looks really good!

Regarding 0. and 1.: Sure, go ahead and rename these however you like. 10 % looks good; we can expose it as a parameter to `AutoGrid` / `EquidistantGrid` eventually.

Regarding 2: We would be in the category `Packing different rectangles in a minimum area rectangle` :https://en.wikipedia.org/wiki/Rectangle_packing. But for now I think we can restrict ourselves to equal sizes.

Regarding 3: Ideally we would nest this in the menu: show only the grid source by default, but enable expanding a sub-menu to control all sources. But I am not sure how feasible this is from the UI-perspective. If we have to decide between one of the two, having a single source is def. better.

Some ideas from my side about what can be done further:
- Add support for an image table. We already have one for the test dataset [here](https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/tables/grid-test-dataset/default.csv).
   - We would need to add this to the bookmark somehow, maybe add an optional field `table` or `gridTable`, that links to the file path?
   - Should we rename the first column from `image_name` to `source_name`?
- How is the connection between the `AutoGrid` and the manual placement of sources in a grid by a user. I think this would fit the `collection` type bookmark well as `manualGrid`.

**Comment by tischi** [comment]
I think it makes sense to split now into several issues:

- [Brightness & Contrast](https://github.com/mobie/mobie/issues/21)
- [Image feature table](https://github.com/mobie/mobie/issues/22)
- [Auto packing](https://github.com/mobie/mobie/issues/23)
- [Auto vs manual grid](https://github.com/mobie/mobie/issues/24)
- [Philosophy of bookmarks](https://github.com/mobie/mobie/issues/25)

**Comment by joshmoore** [comment]
NB: @dragadoncila showed a format for collections of layers (and related [repo](https://github.com/DragaDoncila/napari-compressed-labels-io)) during the morning session yesterday. Videos & notes are on the [topic](https://forum.image.sc/t/next-call-on-next-gen-bioimaging-data-tools-feb-23/48386/9?u=joshmoore) in case syncing up is useful.

**Comment by constantinpape** [comment]
We have a lot of follow-up issues on this one; I will close this for now.
