### ISSUE TITLE
Brightness and Contrast (of Grid View)

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#21]
> Regarding 3: Ideally we would nest this in the menu: show only the grid source by default, but enable expanding a sub-menu to control all sources. But I am not sure how feasible this is from the UI-perspective. If we have to decide between one of the two, having a single source is def. better.

In fact, I was gonna propose to use the existing functionality in BDV for this in order to avoid code and functionality duplication. It has most of what we need, I think.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/2157566/108998964-f0ff2f80-76a1-11eb-8cf7-c2b1da4d9df6.png">

This opens up the question whether we could completely get rid of all our B&C adjustments UI in favor of the standard BDV UI. Initially I implemented them because the old BDV menu was horrible for many sources, but the new one is quite nice.

**Comment by constantinpape** [comment]
> In fact, I was gonna propose to use the existing functionality in BDV for this in order to avoid code and functionality duplication. It has most of what we need, I think.

Yes, the grouping looks like what I had in mind.

> This opens up the question whether we could completely get rid of all our B&C adjustments UI in favor of the standard BDV UI. Initially I implemented them because the old BDV menu was horrible for many sources, but the new one is quite nice.

I wouldn't mind switching to it, if you think that's best way to go. But I guess we would need to extend it a bit, e.g. to support  the 3d viewer control, dataset switching and bookmarks.

**Comment by tischi** [comment]
@K-Meech @constantinpape 

I manged to add it to our UI 😃 

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2157566/109795728-94f35880-7c17-11eb-95c6-bf2259755c0b.png">

The name is the name of the layout key. Is that OK? Or should it be the name of the bookmark?

**Comment by K-Meech** [comment]
Cool!! I'd probably go for the name of the bookmark, otherwise it's easy to lose track of what's being shown

**Comment by constantinpape** [comment]
Great!
I agree with Kimberly, better if it's the name of the bookmark.

**Comment by tischi** [comment]
Since a bookmark can currently contain multiple layouts I am going for this for now: `bookmark.name + "-" + layoutName`. We can change this when we redesign the bookmarks.

**Comment by tischi** [comment]
I am closing now. We could start a new issue in the mobie-fiji-viewer if needed.
