### ISSUE TITLE
Image feature table

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#22]
> Add support for an image table. We would need to add this to the bookmark somehow, maybe add an optional field table or gridTable, that links to the file path? Should we rename the first column from image_name to source_name?

My feeling is that maybe first adding an image feature table to our general specs is a good idea. And then, in a second step we can see how we could use in a "collection view bookmark".

**Comment by constantinpape** [comment]
> My feeling is that maybe first adding an image feature table to our general specs is a good idea. And then, in a second step we can see how we could use in a "collection view bookmark".

That's fine with me, but I think we don't have any really good use case for the image feature table right now besides the grid view. Of course we can also show it in the "normal" mode, but I think it's really important for the grid view because it should enable navigation to the individual sources in the grid.

In terms of spec I would just support a tsv table with a column `source_name` to indicate the source of each column.
```
source_name    column1  column2   ...
image_1         value      ...
image_2         value      ...
...
```
Let me know if you have a different suggestion.

**Comment by tischi** [comment]
>  think we don't have any really good use case for the image feature table right now besides the grid view. 

That's a good point. If that remains to be the case maybe it then rather would be something that lives "inside" the respective bookmark?

**Comment by constantinpape** [comment]
> That's a good point. If that remains to be the case maybe it then rather would be something that lives "inside" the respective bookmark?

Yes, but I don't think we should start to embed tables into the bookmarks json.
I would really like to keep the table format as it is.
I would propose something like this:
```
{
   "collections": {
    "layers": [],
    "layoutType": "",
    "sourceTable": "tables/my-table.csv"
  }
}
```

**Comment by tischi** [comment]
@constantinpape could you please add a table according to your proposal above to our test data?

**Comment by constantinpape** [comment]
Here it is:
https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/tables/grid-test-dataset/default.csv

**Comment by tischi** [comment]
Notes to self: 

Probably I have to on-the-fly create a `SourceAndMetadata` with `metadata.segmentsTablePath` being what's written in the bookmark. 

Then in the BookmarksManger at this place:

```
for ( String layoutName : bookmark.layouts.keySet() )
			{
				final Layout layout = bookmark.layouts.get( layoutName );
				adjustMetadata( sourceNameToSourceAndMetadata, layout, bookmark.name + "-" + layoutName );
			}
```

I should create a source using code such as (from PlateViewer):

```
	private void createImage( )
	{
		BiConsumer< Localizable, IntType > biConsumer = ( l, t ) ->
		{
			t.setInteger( ListItemsARGBConverter.OUT_OF_BOUNDS_ROW_INDEX );

			for ( T annotatedIntervalTableRow : tableRows )
			{
				final Interval interval = annotatedIntervalTableRow.getInterval();
				if ( interval == null ) return;

				if ( Intervals.contains( interval, l ) )
				{
					t.setInteger( annotatedIntervalTableRow.rowIndex() );
				}
			}
		};

		final FunctionRandomAccessible< IntType > randomAccessible =
				new FunctionRandomAccessible( 2, biConsumer, IntType::new );

		rai = Views.interval( randomAccessible, plateInterval );

		rai = Views.addDimension( rai, 0, 0 );

		final RandomAccessibleIntervalSource< IntType > tableRowIndexSource
				= new RandomAccessibleIntervalSource<>( rai, Util.getTypeFromInterval( rai ), "table row index" );

		final ListItemsARGBConverter< T > argbConverter =
				new ListItemsARGBConverter<>( tableRows, coloringModel );

		argbSource = new ARGBConvertedRealSource( tableRowIndexSource , argbConverter );

		contrastLimits[ 0 ] = 0;
		contrastLimits[ 1 ] = 255;
	}
```

Then I would have to implement a different version of this function:
```
private void showAnnotatedLabelsSource( SourceAndMetadata< ? > sam )
    {
        final List< TableRowImageSegment > segments
                = createAnnotatedImageSegmentsFromTableFile(
                     sam.metadata().segmentsTablePath,
                     sam.metadata().imageId );
```

...because the table columns are different than for the normal image segments.

I probably need put add a `Map< SourceName, Interval >` to the metadata.

Updating the growing metadata is becoming annoying, maybe I should for now just add a `Map< String, Object >` for such things and then we can later consolidate.

**Comment by tischi** [comment]
@constantinpape Could you please also refer to this table in the bookmark?

**Comment by constantinpape** [comment]
https://github.com/mobie/covid-tomo-datasets/blob/grid-test/data/grid-test-dataset/misc/bookmarks/default.json#L13
Go ahead and change the fieldname if you prefer something else.

**Comment by tischi** [comment]
@constantinpape do we always have it such that we repeat the dataset name again?

<img width="856" alt="image" src="https://user-images.githubusercontent.com/2157566/109976208-ce04f900-7cfb-11eb-8d5b-30692cd66640.png">

**Comment by constantinpape** [comment]
> @constantinpape do we always have it such that we repeat the dataset name again?

No, everything that comes after "tables" is pretty arbitrary (at least for now).

**Comment by constantinpape** [comment]
@tischi I realized that the table layout proposed here https://github.com/mobie/mobie/issues/22#issuecomment-785307077
will probably not work for our new grid views:
The grid can have multiple sources per position, so we cannot have `source_name` as the main column.
Instead I would propose this:
```
grid_id    column1  column2   ...
0             value      ...
1             value      ...
...
```
with `grid_id` refering to the list index of `sources` in `autoGrid`, i.e.
```json
{"autoGrid":{
  "sources": [["source1", "source2"], ["source3", "source4"]]
}}
```

**Comment by constantinpape** [comment]
This is done.
