### ISSUE TITLE
Bookmarks / Views / Layouts 

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#25]
Also with regard to thinking about the NGFF discussions I wonder whether the concept of a "Bookmark" should rather be seen as a "View" on a (subset of) collection of images.

Essentially, the idea is that there is a flat list of images and then somewhere else there is a list of "various suggestions" as to how to layout and display these images in meaningful ways. This is what we have as "Bookmarks", but I think calling it "Views" would give it a different touch.

**Comment by constantinpape** [comment]
> Also with regard to thinking about the NGFF discussions I wonder whether the concept of a "Bookmark" should rather be seen as a "View" on a (subset of) collection of images.

I think that's a good summary of our bookmark concept, but "View" is maybe not such a good name because we already use it to refer to the viewer transformation. (We could of course change that, but I find this meaning pretty intuitive).
I am not sure what would be a better name, I will think about it.

I think our whole bookmark spec has become a bit unstructured, maybe we can discuss reorganising it too once we have a first version of the collections we are happy with.

**Comment by constantinpape** [comment]
Connected to this: we should also rethink the image metadata in `images.json`.
@tischi could you link to the relevant part in the code for image and bookmark metadata.

**Comment by tischi** [comment]
Bookmark: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bookmark/Bookmark.java

Layout: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bookmark/Layout.java

LayoutType: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/bookmark/LayoutType.java

MutableImageProperties: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/image/MutableImageProperties.java

ImageProperties: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/image/ImageProperties.java

Metadata: https://github.com/tischi/imagej-utils/blob/eeea86750ed3307f204d8753675e0eeab3e9ab5c/src/main/java/de/embl/cba/bdv/utils/sources/Metadata.java
- Note: Metadata is sort of legacy and currently is constructed from ImageProperties by means of a MetadataImagePropertiesAdaptor, i.e. they should be redundant (even if in practice they are currently not, i.e. it is a mess).

SourceAndMetadata: https://github.com/tischi/imagej-utils/blob/master/src/main/java/de/embl/cba/tables/image/SourceAndMetadata.java
- This is a most critical object, because we essentially `MoBIE.show( sourceAndMetadata );`, that means this currently must contain all information needed to show the source (and the table if it is a label image).


SourcesModel: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/image/SourcesModel.java

I'll just add stuff to this post that I may have forgotten.

**Comment by constantinpape** [comment]
Also relevant: grouping by field instead of image name,
see https://github.com/mobie/mobie-viewer-fiji/issues/200.

**Comment by constantinpape** [comment]
New spec is already way under way
