### ISSUE TITLE
Support time series

### ISSUE THREAD

**Issue by constantinpape** [mobie-org/mobie#26]
What about time series?
What would we need to change to support it.

I will look into setting up an example dataset.

**Comment by constantinpape** [comment]
Ok, I found a good example project for this, with lightsheet timeseries data with additional segmentations and tracking information.
I can upload it, but we should decide first how we represent the timeseries.
I can think of two options right now:
1. Follow the BDV approach, i.e. the volumes for different time series are in the same container located at `setup0/timepoint0`, `setup0/timepoint1`, ...
2. Add the timeseries volumes as separate containers and add them as a collection bookmark with a new layout type `timeseries`.

Similarly, we will need to think about how to store the tables for the segmentations in the different timepoints.

What do you think @tischi @K-Meech?

**Comment by tischi** [comment]
I think, to start with, we should treat a time series as a single 4D image (following the BDV approach) and have just one table for all time points, with a `time_point` column. This would work best with the Java code, where a `Source` is a 4D image. To see how that looks like in BDV N5 we can just save a time series image as N5 in Fiji.
**Plugins › BigDataViewer › Export Current Image as XML/N5**

**Comment by constantinpape** [comment]
> To see how that looks like in BDV N5 we can just save a time series image as N5 in Fiji.

I know how it's saved already ;).

**Comment by K-Meech** [comment]
Sounds good! The BDV approach sounds like the easiest for now + one table for all timepoints.

**Comment by constantinpape** [comment]
I have uploaded a dataset with a timeseries now with 50 timepoints: 
https://github.com/mobie/arabidopsis-root-lm-datasets

The timepoint layout follows the bdv pattern which is `setup0/timepoint<TP-ID>/s...`. There are three volumes: membrane and nuclei marker imaged in lightsheet and a segmentation based on the membrane channel. For the segmentation we have a table that contains:
```csv
label_id, timepoint, track_id, ...
1, 0, 1, ...
2, 0, 0, ...
1, 1, 1, ...
```
where `track_id` is the id derived from manual tracking via mamut.

@tischi let me know if you need anything else to test MoBIE with timeseries.

**Comment by tischi** [comment]
Thanks. This is great and after a few minor fixes already working in the latest master.
