### ISSUE TITLE
Organisation name

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#3]
@constantinpape 

mobie-org seems to be free. I could live with this.

**Comment by constantinpape** [comment]
Works for me. Should we rename it right now?

**Comment by tischi** [comment]
Why not:

1. since the platybrowser name will still work it does not matter that much
2. if mobie without the org becomes free we can use still later

I will rename now.

**Comment by tischi** [comment]
Done. I'll leave the issue open until we hear back from the github team about the name without the org....

**Comment by constantinpape** [comment]
I think we are all happy with `mobie-org` now.
