### ISSUE TITLE
Mobie mascot

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#4]
Hi All,

@constantinpape @K-Meech @vzinche @HernandoMV 

We need a mascot for the new MoBIE framework.

Maybe something like below:
https://www.alamy.de/cartoon-happy-wal-image236279830.html

Any suggestions and drawings are welcome :-)

**Comment by constantinpape** [comment]
I know I sound like a broken record, but I want it to have a magnifying glass in it's flipper ;)

**Comment by constantinpape** [comment]
And I think it should be only grayscale to look a bit professional ;)

**Comment by vzinche** [comment]
:+1: for the magnifying glass. Or maybe even a monocle to go fancy :smile:

**Comment by HernandoMV** [comment]
![mobie_v12-04](https://user-images.githubusercontent.com/6049065/83495768-0c8d2f00-a4b0-11ea-8447-b61987136a40.jpg)

**Comment by HernandoMV** [comment]
![mobie_v1-03](https://user-images.githubusercontent.com/6049065/83495796-14e56a00-a4b0-11ea-90c6-947bbf0bfc95.jpg)

**Comment by HernandoMV** [comment]
![mobie_v1-02](https://user-images.githubusercontent.com/6049065/83495804-17e05a80-a4b0-11ea-9c97-b7adc75434c7.jpg)

**Comment by HernandoMV** [comment]
![mobie_v1-01](https://user-images.githubusercontent.com/6049065/83495811-1ca50e80-a4b0-11ea-9f28-bad6abd1eeb8.jpg)

**Comment by HernandoMV** [comment]
Current suggestions:
- add a happy face to the whale
- put the loupe in front of the eye (or a monocle - should this go with a top hat? :) )

**Comment by vzinche** [comment]
Wow you should really get Gemma a cake for this!

My comments:
* I agree that the whale should have a face, or a smile
* I would make the magnifying glass smaller, not to reach the whales top: see a shitty proto-picture
![photo5382243631852793258](https://user-images.githubusercontent.com/32451366/83499177-38fb7800-a4bd-11ea-811e-24d216015801.jpg)
* Regarding the color scheme I really like [this](https://github.com/mobie-org/mobie/issues/4#issuecomment-637366662). But the black-white version also looks pretty stylish

**Comment by HernandoMV** [comment]
Some ideas (just for the whale, we can implement color schemes and background later:

![mobie_v2](https://user-images.githubusercontent.com/6049065/83503326-cd181000-a4ba-11ea-83f8-0392a3eed263.jpg)

Preferences and suggestions?

**Comment by tischi** [comment]
- I think something along the lines of `v2-03` would go into the right direction.
- The eye of `v2-07` looks a bit happier for my taste :)
- Could one try to make it look even more happy? Bigger smile?
- Maybe the loupe could be a tad more subtle.
- Right now the whale looks at you, maybe it could rather look more down (on the data) as in Valentyna's sketch?

**Comment by constantinpape** [comment]
my favorites are also `v2-02` or `v2-03`, I agree with @tischi's points above, but looks really good already!

**Comment by GemmaEG** [comment]
Hello! :) 
New suggestions including:
- other eye (looking down/straight and grey/blue)
- different smiles 
- added color background

Let me know what you think!

![mobie_v2-2](https://user-images.githubusercontent.com/66318981/83534263-893bff80-a4e8-11ea-80be-0fdde1f9e320.jpg)

**Comment by constantinpape** [comment]
They all look great! I like `b` best.

**Comment by tischi** [comment]
I also like `b` the best.
And personally, I like some simple blue color scheme, along those lines:
![image](https://user-images.githubusercontent.com/2157566/83541812-6d415980-a4fa-11ea-819d-96a27094abc8.png)

**Comment by GemmaEG** [comment]
So here is b with some blue color scheme tests
![mobie_v3](https://user-images.githubusercontent.com/66318981/83615317-4b89b600-a57e-11ea-871e-53ca5663f294.jpg)

**Comment by vzinche** [comment]
G is my favorite one!

**Comment by constantinpape** [comment]
All look great! I would also go with G

**Comment by tischi** [comment]
@GemmaEG 
I also like G! 
Could you try to make the contrast between the colors a little bit less strong?
Maybe try to make the blue of the body a bit lighter?

**Comment by tischi** [comment]
and, looking back I think this guy is also very sweet. 
Could we also see a coloured version of this one and a simplified loupe (_without_ the shadow effects)?

![image](https://user-images.githubusercontent.com/2157566/83630517-31f76700-a59c-11ea-97f8-f4c9f4b11efa.png)

I think this one ^^ also is nice because the mouth does not touch the loupe.

**Comment by GemmaEG** [comment]
I am not sure I got what you wanted regarding the contrast, but here are a couple of different shades of blue. Also with the other eye
I personally think the color scheme in G/G1 look best colorwise.

If this is not what you wanted me to try please let me know! We can keep on iterating :) 
![mobie_v4](https://user-images.githubusercontent.com/66318981/83749294-6716be80-a65b-11ea-857d-c59cf7b3389e.jpg)

**Comment by constantinpape** [comment]
I like G5 best. But I would be very happy to use any of these!

**Comment by tischi** [comment]
@GemmaEG
thanks :-) 

1. in v2-02 there is a bit more distance between the end of the mouth than in the new version. I like that better.... Maybe this can be achieved by making the loupe a little bit thinner?
2. regarding this colors, yeah maybe we just leave it like in G1.

So, in summary: G1 but with a little bit thinner loupe.

**Comment by GemmaEG** [comment]
Here are the files for both G1 and G5 with slimmer magnifying glass
Glad I could help getting you a happy mascot
If you see something wrong or want something else, let me know!
[G1_G5.zip](https://github.com/mobie-org/mobie/files/4736431/G1_G5.zip)

**Comment by constantinpape** [comment]
Thanks so much!
I really like `G5_T`, I think we should go with it :).

**Comment by tischi** [comment]
![image](https://user-images.githubusercontent.com/2157566/83883655-1202a780-a744-11ea-8fcb-88a36ecffa1f.png)
![image](https://user-images.githubusercontent.com/2157566/83883684-1c24a600-a744-11ea-957f-b835a0e110fb.png)

Very nice! Hard choice. Maybe the lower one?
What do the others think?

**Comment by vzinche** [comment]
I really like both of them :smiley:

**Comment by K-Meech** [comment]
They both look great! I'd probably go for the lower one. Thanks so much Gemma! 😄

**Comment by GemmaEG** [comment]
No probs! 
Glad you like it! :D

**Comment by tischi** [comment]
![image](https://user-images.githubusercontent.com/2157566/83895460-02d72600-a753-11ea-8a9f-1cf5c2b15ebf.png)

**Comment by tischi** [comment]
...I replaced the background color by the light grey of the github. It takes a while to update. But I think that will look even nicer.

**Comment by tischi** [comment]
there we go: 
![image](https://user-images.githubusercontent.com/2157566/83895966-ba6c3800-a753-11ea-9722-645f508aca1e.png)

**Comment by yanschwab** [comment]
This is just brilliant!!!! Bravo les artistes

**Comment by tischi** [comment]
I flipped it such that it looks more into our repo and not outside of it, where there is nothing to see. I can change it back if people object.

But give yourself some time. It always comes as a shock when first looking at a flipped image where one got used to the other orientation.

**Comment by constantinpape** [comment]
I like the rotated version :)

**Comment by tischi** [comment]
Me too, I think it makes the website look more compact.

**Comment by tischi** [comment]
Now also here: https://imagej.net/MoBIE
As cute as ever.
@GemmaEG
