### ISSUE TITLE
image location and table location

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#8]
@constantinpape @K-Meech @vzinche @martinschorb

Do we really need the opening modality where one can enter two different locations for the images and tables?

Could we cover the current use-cases also with such a UI?

`Project location: free text`
`Open images from: remote/local`
`Project branch: free text (master)`

Then you could put your local version in the project location such that this would be used for loading the tables, but the images could be loaded either locally or from s3.

Also I wonder whether having the option to specify a github branch may be an option to entirely get rid of the need to open from local?

**Comment by martinschorb** [comment]
sounds good to me

**Comment by vzinche** [comment]
Sorry, I didn't get what's the difference between `Project location` and `Project branch`?

**Comment by tischi** [comment]
branch = github branch. 
that means you can have your own branch next to master.

**Comment by vzinche** [comment]
Yes, but which of those is used to load the tables?

**Comment by tischi** [comment]
The tables are always loaded from the `Project location`.
Example 1: `/g/kreshuk/data` (in this case the branch would be ignored).
Example 2: `github/something` (from the specified branch ).

**Comment by vzinche** [comment]
Than why do we need the `Project branch` at all?

**Comment by tischi** [comment]
Because we want to have test branches on github to try out new features.

**Comment by tischi** [comment]
And maybe you want to have a special branch with some of your tables.

**Comment by K-Meech** [comment]
Hey - my current workflow is to test things in a fork of the main repo, so I can add whatever tables I want without cluttering up the main repo for everyone else. Then it's useful to have the separate data location, as I can load the data from the common share, and the tables from my own fork. I guess under this new system this wouldn't be supported? I'd need to test everything in a branch of the main repo?

**Comment by tischi** [comment]
>I can load the data from the common share

Do you mean the image data?

That means you want to:

1. Load the table data from a github fork
2. Load the image data from local?

Yeah, the issue there would be that the software cannot know the path to your local image data because as `Projection location` you would need to specify the github location.

Super confusing.....

**Comment by tischi** [comment]
@K-Meech 
Do you see any way to simplify this?
Because otherwise, in principle, I would even need to support different branches for both image and table data locations. I think this could become too confusing.

**Comment by K-Meech** [comment]
Yes - I mean the image data. It's nice to load this from the common share - as it is rather large! 

So in my current workflow I need to:
-load the table data from a github fork
-load the image data from a local copy of the main repo

I think Valentyna does a similar kind of thing too?
I guess the simplest way to get around this, would be for us to each have a branch in the main repo for testing. But it does make it a bit harder to look at rough results quickly in the browser...

**Comment by vzinche** [comment]
Sorry, I am fully lost here, I still don't get why we replace two options with three options now. 
Do you want to specify a branch you load the mobie viewer from? If not, why would we ever need to specify the `Project branch` if we can give the github repo path to the `Project location`?

**Comment by vzinche** [comment]
Regarding the `Open images from: remote/local` I am completely fine with it, because I am mostly modifying the tables, not the images, so just specifying the github path should be enough. 
And even when I do modify the images, I could always use the local (/g/arendt/EM_6dpf_segmentation/platy-browser-data/) for testing, the outer world won't see it anyways.

**Comment by martinschorb** [comment]
OK, what are the scenarios:

image data:
1) local
2) remote

table data:
a) local (git branch)
b) remote (git branch)

- image data is always independent of the git branch (ignored)

Scenarios:

1-a : ```Project location```points to the local directory

1-b: does not work in the proposed way, as there can be no remote address specified if it points to the local directory.

2-a: ```Project location```points to the local directory, this would load the image data from s3 and the tables locally (nice to play around). No need to specify any branches though, because the one that is currently checked out will be presented to mobie.

(```Project location```points to the remote git: does not work because the local directory is unknown)

2-b: ```Project location```points to the remote git repo. Image data is fetched from s3
This is the only scenario that would require a git branch to be specified.

I don't think this is really needed, because the 2-a scenario with a locally checked out copy of the desired branch is always easy to provide.

So all we really need is ```Project location``` and (maybe even conditionally if a local location is given) an option to load image data from remote.

**Comment by constantinpape** [comment]
Sorry, I did not fully understand this whole discussion. But I don't really understand why we need to change it so much from what we have right now:
```
- Image Data Location
- Table Data Location
-- Table Data Branch (optional will only be taken into account if it's a git url, not for local)
```
Both support git url and local.

If you don't like `Location`, replace it by `Project`, I don't mind.
In addition, we move this to `Expert` or `Advanced` mode.

-> Very little changes to the old system and it supports all we need.

**Comment by tischi** [comment]
Specifying a `-- Table Data Branch` is not really working, because many things like the Bookmarks are more image specific and they could live on a branch....

Maybe it is so confusing because we are in fact loading **three** things, not only **two**.

1. General information about the project, i.e. which datasets exists, what are the data set names, and, e.g., the bookmarks (essentially everything that is in .json files).
2. Image data (**remote** on s3 is fully specified by xml, **local** on drive only by relative path)
3. Table data (**remote** on git and **local** on drive are both specified by relative path) 

Does that make sense?

**Comment by constantinpape** [comment]
> Maybe it is so confusing because we are in fact loading **three** things, not only **two**.
> 
>     1. General information about the project, i.e. which datasets exists, what are the data set names, and, e.g., the bookmarks (essentially everything that is in .json files).
> 
>     2. Image data (**remote** on s3 is fully specified by xml, **local** on drive only by relative path)
> 
>     3. Table data (**remote** on git and **local** on drive are both specified by relative path)
> 
> 
> Does that make sense?

Ok, I see your point now.
But we can have incosistencies as soon as we allow to specify any of these things separately from each other. (E.g. tables for an image can be missing etc.).

I don't think we should worry about this here, that's why it goes to advanced mode; whoever uses it needs to make sure that the combination that is loaded is consistent.

**Comment by tischi** [comment]
> I don't think we should worry about this here, that's why it goes to advanced mode; whoever uses it needs to make sure that the combination that is loaded is consistent.

Yes, anyway. But I am still wondering how a sensible UI for the advanced mode should look like. 
Because the current one, with image data location and table data location is confusing to me and my code, because it is not clear where the project information comes from.

**Comment by constantinpape** [comment]
> But I am still wondering how a sensible UI for the advanced mode should look like.
> Because the current one, with image data location and table data location is confusing to me and my code, because it is not clear where the project information comes from.

I see. I can think of two options:
- Rename `Table -> Metadata` and then get project information and tables from there
- Have 3 different ones: `ProjectData`, `ImageData`, `TableData`. All three support local / git and if they are on git you can also specify a branch.

I would go for the 2nd option. It introduces a few more fields, but it's unambiguous.

**Comment by tischi** [comment]
> Have 3 different ones: ProjectData, ImageData, TableData. All three support local / git and if they are on git you can also specify a branch.

Sounds good to me. Looking at my code it seems this can be implemented, and, in fact, seems to resolve a few confusing choices that I was making in the past.

What do the others think?

**Comment by K-Meech** [comment]
Sounds good to me!

**Comment by tischi** [comment]
...and one more question: If the `ImageDataLocation` is a github repo then I should imply that the data should be loaded from S3, right? I am asking because this is just a convention and not really forced. Both the local copy of the repo and the repo on github contain the same information to load the data from S3 (there is a sub-folder `local` and `remote` below `images` in both cases). 

What I currently have in my code is:

```
storageModality = imageDataLocation.startsWith( "http" ) ? "remote" : "local";
```

where "remote" means "load from S3" and "local" means load from disk.
I don't really like this, because it is implicit. Maybe we still did not find the best logic...
Also we could not really support Martin's `2a` scenario, I think.
I'll think a bit more ;-)

**Comment by constantinpape** [comment]
> ```
> 
> ```
> 
> 
> where "remote" means "load from S3" and "local" means load from disk.
> 
> I don't really like this, because it is implicit. Maybe we still did not find the best logic...
> 
> Also we could not really support Martin's `2a` scenario, I think.
> 
> I'll think a bit more ;-)

I see.
We could add another check-box `load from s3`.

**Comment by tischi** [comment]
Maybe like this? Not easy, but it is the "Expert" mode.

```
Project location (github or local): free text
Project branch (for github): free text, default: "master"
Load image data from: choice: "s3", "local"
Image data root path (for local): free text
Table data location (github or local): free text
Table data branch (for github): free text, default: "master"
```

**Comment by constantinpape** [comment]
Yes, I think that's good. But I would reorder:
- Project location
- Project branch
- Table location
- Table branch
- Load image data checkbox
-- Image data root (only if checkbox is "local")

**Comment by tischi** [comment]
Ok, in fact, I though about this. The reason I did not do it like this was because I wanted it to be more clear that the (relative) image paths are fetched from the `Project` and **not** from the `Table`s. But since the experts should know this, I think we can use your version, because it does look a bit prettier.

**Comment by vzinche** [comment]
Sounds good to me, but now I don't get why we should specify a `Project/Table branch` in a separate field instead of just giving the `Project/Table location` as a github path including the branch, i.e. `https://github.com/vzinche/platybrowser-backend/raw/correct_vc`

**Comment by constantinpape** [comment]
> Sounds good to me, but now I don't get why we should specify a `Project/Table branch` in a separate field instead of just giving the `Project/Table location`

We will only specify the parent repository from now on, so that users don't need to specify the whole raw path, which is confusing.

**Comment by tischi** [comment]
@constantinpape @K-Meech @vzinche 
I am working on this today.
Do we have a project with a working git branch that I can use for testing?

**Comment by constantinpape** [comment]
This combination should work:
`https://github.com/mobie/covid-tomo-datasets`
`norm-bookmarks`

**Comment by tischi** [comment]
Thanks!

```
Project location (github or local): free text
Project branch (for github): free text, default: "master"
Load image data from: choice: "s3", "local"
Image data root path (for local): free text
Table data location (github or local): free text
Table data branch (for github): free text, default: "master"
```

And any maximally complicated combination to test all of above?

**Comment by constantinpape** [comment]
Yes, that should cover everything. Some comments:

> Load image data from: choice: "s3", "local"

Only relevant for local, on github we can only load from s3.

> Image data root path (for local): free text

Would you specify this as another full path or w.r.t. "Project location"?
Also, I think this is relevant for github as well, because this determines where to look for the `datasets.json`, which are usually not in the project root, but in `data` (and they could be somewhere else).

**Comment by tischi** [comment]
> Only relevant for local, on github we can only load from s3.

I am not sure, because you could select github as the location where all the project information (e.g. bookmarks) are stored but still load the images from the local file system.

-------

I think this still is so confusing that it is better to work from concrete use-cases rather than discussing in general 😸 

@K-Meech @vzinche @constantinpape @martinschorb 
Could you please provide relevant examples (for your work) how you would like to load the data (if possible using below fields) such that I could test whether they all work?

```
Project location (github or local): free text
Project branch (for github): free text, default: "master"
Load image data from: choice: "s3", "local"
Image data root path (for local): free text
Table data location (github or local): free text
Table data branch (for github): free text, default: "master"
```

**Comment by vzinche** [comment]
+1 for having github both s3 and local

My common usage:
```
Project location (github or local): "https://github.com/mobie/platybrowser-datasets"
Project branch (for github): "master"
Load image data from: choice: local
Image data root path (for local): "/g/arendt/EM_6dpf_segmentation/platy-browser-data"
Table data location (github or local): "https://github.com/vzinche/platybrowser-backend"
Table data branch (for github):"bookmarks"
```


To test the case when the `Project location` is different from the `Image data root path`, maybe we could have something like we had for David? When the are some local files that get loaded from the branch `david` only, not from the `master`?

**Comment by vzinche** [comment]
Additionally, what do you think of renaming `Image data root path` to `Image data location`?
Because if you load everything from local it is completely unclear that `Project location` and `Image data root path` stand for the same thing

**Comment by constantinpape** [comment]
> I am not sure, because you could select github as the location where all the project information (e.g. bookmarks) are stored but still load the images from the local file system.

Ok, I think I misunderstood what's loaded from `Project`, `Image Data Location` and `Table Data Location`.
I think what you propose makes sense now, but I agree with @vzinche that should maybe rename `Image data root path` to `Image data location`.

**Comment by constantinpape** [comment]
Here is one example where the image data is only available locally:

```
Project location (github or local): "https://github.com/mobie/platybrowser-datasets"
Project branch (for github): "xray"
Load image data from: choice: local
Image data root path (for local): "/g/arendt/EM_6dpf_segmentation/platy-browser-data"
Table data location (github or local): "https://github.com/mobie/platy-browser-data"
Table data branch (for github): "xray"
```

It should also work if you replace "https://github.com/mobie/platy-browser-data" with "/g/arendt/EM_6dpf_segmentation/platy-browser-data" everywhere (then loading everything from the local path).

**Comment by tischi** [comment]
OK! Please test within `MoBIE-beta` and let me know. I also changed some other minor things. You will see.

**Comment by constantinpape** [comment]
I just tested, and it works. The other changes in the menu look good too!

**Comment by vzinche** [comment]
Worked well for me too!
The only question is: how much do we need separate `Project branch` and `Project expert mode`? If you just want to specify the branch, can't you just change it in the settings of the `Project expert mode`?

**Comment by K-Meech** [comment]
Works for me too! Looks good

**Comment by constantinpape** [comment]
> The only question is: how much do we need separate `Project branch` and `Project expert mode`? If you just want to specify the branch, can't you just change it in the settings of the `Project expert mode`?

I think that can be quite useful in order to set up something for a collaborator on a different branch without exposing them to all the options in the expert mode.

**Comment by vzinche** [comment]
@tischi, one thing doesn't work for me:
I have [a fork](https://github.com/vzinche/platybrowser-backend/tree/bookmarks) of platybrowser-datasets that is identical to its parent, except I modified the bookmarks. I want to test these bookmarks.
When I put the address of this branch to advanced MoBIE's `Table Data Location`, it doesn't show me the updated bookmark, so I guess they are taken from `Project Location`.
But when I put the address of this branch to `Project Location` it throws me the following exception:
![Screenshot from 2020-09-23 10-46-39](https://user-images.githubusercontent.com/32451366/93989398-25389200-fd8a-11ea-9aac-330dbc602b49.png)
What am I doing wrong?

**Comment by constantinpape** [comment]
I think all of this is solved.
